spring:
  application:
    name: sistema-de-agendamentos
  datasource:
    url: jdbc:mysql://localhost:3306/appointment?createDatabaseIfNotExist=True
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true